# Generated by Django 5.2.1 on 2025-05-28 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='curiouspeople',
            name='tried_to_see_users_at',
            field=models.DateTimeField(auto_now_add=True, default='2025-05-05 04:04'),
            preserve_default=False,
        ),
    ]
