# Generated by Django 5.2.1 on 2025-05-27 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='planet',
            name='slug',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
