# Generated by Django 5.2.1 on 2025-05-27 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stars', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='star',
            name='image',
            field=models.ImageField(default='stars/default.jpg', upload_to='stars'),
        ),
    ]
